# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tugas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tugas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btugas.proto\x12\x07tugasdb\"\x1c\n\x0ePegawaiRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"V\n\x0fPegawaiResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04kode\x18\x02 \x01(\t\x12\x0c\n\x04nama\x18\x03 \x01(\t\x12\r\n\x05\x61ktif\x18\x04 \x01(\x08\x12\x0c\n\x04gaji\x18\x05 \x01(\x02\x32Q\n\x0ePegawaiService\x12?\n\nGetPegawai\x12\x17.tugasdb.PegawaiRequest\x1a\x18.tugasdb.PegawaiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tugas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEGAWAIREQUEST']._serialized_start=24
  _globals['_PEGAWAIREQUEST']._serialized_end=52
  _globals['_PEGAWAIRESPONSE']._serialized_start=54
  _globals['_PEGAWAIRESPONSE']._serialized_end=140
  _globals['_PEGAWAISERVICE']._serialized_start=142
  _globals['_PEGAWAISERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
