events {
    worker_connections 1024;
}
http {
    upstream my_backend {
        server backend_app:8000;
    }
    
    server {
        listen 80;
        location / {
            proxy_pass http://my_backend;
        }
    }
}