events {
    worker_connections 4096;
}
http {
    # Definisi grup backend
    upstream backend {
        server bs_app:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}